<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-SB5APSLQ" failures="2" tests="2" name="Default test(failed)" time="0.047" errors="0" timestamp="2022-11-23T17:36:39 IST">
  <testcase classname="failedtestng.NewTest" name="j" time="0.007">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at failedtestng.NewTest.j(NewTest.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- j -->
  <testcase classname="failedtestng.NewTest" name="h" time="0.0">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at failedtestng.NewTest.h(NewTest.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- h -->
  <testcase classname="failedtestng.NewTest" name="f" time="0.0">
    <ignored/>
  </testcase> <!-- f -->
  <testcase classname="failedtestng.NewTest" name="i" time="0.0">
    <ignored/>
  </testcase> <!-- i -->
</testsuite> <!-- Default test(failed) -->
